---
name: "🛠️ DevOps issue"
description: Automation, CI/CD, GitHub Apps, etc.
labels:
  - devops
body:
  - type: dropdown
    id: type
    attributes:
      label: Type
      description: Request type
      options:
        - Automation
        - CI/CD
        - GitHub Apps
        - GitHub Checks
        - Other
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please, describedetails of youor request.
    validations:
      required: true
