---
name: "🚀 Feature request"
description: Suggest an idea for this project.
labels:
  - enhancement
  - new
body:
  - type: textarea
    id: description
    attributes:
      label: "Feature Request"
      description: Is your feature request related to a problem?
      placeholder: |
        A clear and concise description of what the problem is.
        Ex. I'm always frustrated when...
      value: N/A
    validations:
      required: false
  - type: textarea
    id: proposal
    attributes:
      label: "Proposal"
      description: If you have a solution in mind, please describe it.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: "Alternatives"
      description: Have you considered any alternative solutions or workarounds?
      value: N/A
    validations:
      required: false
  - type: textarea
    id: additional
    attributes:
      label: "Additional context"
      description: Add any other context about the problem here.
      value: N/A
    validations:
      required: false
